### ISSUE TITLE
Arrows don't line up with mhchem package

### ISSUE THREAD

**Issue by krrk** [firamath/firamath#32]
When using the mhchem package to write chemical equations the arrows don't line up properly. The problem exists in both the Light and standard weights. I didn't check the other weights. Here is an MWE:

```latex
%! TEX program = lualatex
\documentclass[varwidth=true, border=10pt, convert={size=640x}]{standalone}
\usepackage[version=4]{mhchem}
\usepackage{unicode-math}
\setmainfont{Fira Sans Light}
\setmathfont{Fira Math Light}

\begin{document}
\ce{A <=> B + C}
\vspace{5mm}
\ce{A <-->[long forward]B + C}
\vspace{5mm}
\ce{X <-->Y + Z}
\end{document}
```
![arrows-1](https://user-images.githubusercontent.com/4636304/54408889-452dc680-46ba-11e9-85f3-e6740e29e6ac.png)

**Comment by RuixiZhang42** [comment]
No need to test with the `mhchem` package.

```tex
\documentclass{article}
\usepackage{amsmath}
\usepackage{unicode-math}
\setmathfont{[FiraMath-Thin.otf]}[version=Thin]
\setmathfont{[FiraMath-UltraLight.otf]}[version=UltraLight]
\setmathfont{[FiraMath-ExtraLight.otf]}[version=ExtraLight]
\setmathfont{[FiraMath-Light.otf]}[version=Light]
\setmathfont{[FiraMath-Book.otf]}[version=Book]
\setmathfont{[FiraMath-Regular.otf]}[version=Regular]
\setmathfont{[FiraMath-Medium.otf]}[version=Medium]
\setmathfont{[FiraMath-SemiBold.otf]}[version=SemiBold]
\setmathfont{[FiraMath-Bold.otf]}[version=Bold]
\setmathfont{[FiraMath-ExtraBold.otf]}[version=ExtraBold]
\setmathfont{[FiraMath-Heavy.otf]}[version=Heavy]
\setmathfont{[FiraMath-Ultra.otf]}[version=Ultra]
\newcommand\test[1]{%
  \begingroup
  \makebox[5.775em][l]{\texttt{#1}}\mathversion{#1}%
  $A \xrightarrow{\quad f\quad} B$\par
  \endgroup
}
\begin{document}
\test{Thin}%
\test{UltraLight}%
\test{ExtraLight}%
\test{Light}%
\test{Book}%
\test{Regular}%
\test{Medium}%
\test{SemiBold}%
\test{Bold}%
\test{ExtraBold}%
\test{Heavy}%
\test{Ultra}%
\end{document}
```

![arrows](https://user-images.githubusercontent.com/39968857/54483980-8bf2fc00-4833-11e9-822c-666cfbf94bd6.png)

All weights **except for Regular** experience the misalignment. Possibly because the arrows in other weights were just recently added and the vertical positions were not tuned to be the same as the minus sign (long arrows are usually built by combining minus and arrow).

**Comment by RuixiZhang42** [comment]
The Regular weight has problem too: The thicknesses between the extended line and the arrow line are not the same. The arrow is thicker.

**Comment by stone-zeng** [comment]
`amsmath` uses minus sign (U+2212) to construct `\xrightarrow` and `\xleftarrow`. The same is for `xRightarrow` and `xLeftarrow` in `extarrows`, which uses equal sign. I haven't adjusted these glyphs so that they can be consistent. 

Actually, this is a kind of hack (extended arrow has nothing to do with minus and equal!) which should be avoided in "pure" unicode-math. However, since there is no way to (easily) use "real" extended arrows (see <https://tex.stackexchange.com/q/423893>), I think I need to make a compromise to make them consistent.

**Comment by RuixiZhang42** [comment]
@stone-zeng Yep, the good old `amsmath` as well as the Computer Modern family all use the same hack: Long `\Rightarrow` is pieced together using equal signs and long `\rightarrow` using minus signs. Another “due to historical reason” situation I’m afraid. The legacy packages have to work with limited glyph space, unlike the current Unicode implementation.

Hopefully `unicode-math` will take care of this… someday…

**Comment by stone-zeng** [comment]
![Screen Shot 2021-06-13 at 03 39 55](https://user-images.githubusercontent.com/18233088/121787516-08ced500-cbf9-11eb-9eb0-1c3615a72c08.png)
![Screen Shot 2021-06-13 at 03 37 52](https://user-images.githubusercontent.com/18233088/121787466-bdb4c200-cbf8-11eb-9dcc-bb375f4fd6dc.png)
![Screen Shot 2021-06-13 at 03 40 30](https://user-images.githubusercontent.com/18233088/121787527-1c7a3b80-cbf9-11eb-9fea-1649c94f94f9.png)
